### ISSUE TITLE
Errors installing pygom on Mac (setup.py generating error)

### ISSUE THREAD

**Issue by funkedavid82** [ukhsa-collaboration/pygom#61]
I work with Martin Grunnil and he has opened a previous issue (#58) on this subject on my behalf.
In addition, no one has been able to use pygom on Mac in my lab. See the errors bellow. Thank you in anticipation.

**Traceback (most recent call last):
  File "setup.py", line 105, in <module>
    scripts=[]
  File "/Applications/Anaconda3/anaconda/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/Applications/Anaconda3/anaconda/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Applications/Anaconda3/anaconda/lib/python3.5/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/Applications/Anaconda3/anaconda/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/Applications/Anaconda3/anaconda/lib/python3.5/site-packages/setuptools/dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Applications/Anaconda3/anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/Applications/Anaconda3/anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/jummy30/Documents/nextcloud/MacDocBK/YORK_PDV_FIELDS/Martin/PYGOM/pygom-master/.eggs/setuptools_scm-6.4.2-py3.5.egg/setuptools_scm/__init__.py", line 90
    version: Optional[ScmVersion]
           ^
SyntaxError: invalid syntax**

**Comment by m-d-grunnill** [comment]
Within the setup.py file try replacing line 82:

```
    use_scm_version=True,
```
with:
```
    version=0.17,
```

**Comment by twomagpi** [comment]
Would be good to know if this works for Mac (we have no access to a Mac) so very hard to debug and CI setup is non-trivial.
