### ISSUE TITLE
timeout when executing notebook

### ISSUE THREAD

**Issue by hareball90** [ukhsa-collaboration/pygom#98]
stochastic.ipynb error log

Traceback (most recent call last):
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\nbclient\client.py", line 776, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\jupyter_core\utils\__init__.py", line 184, in ensure_async
    result = await obj
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\jupyter_client\channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\nbclient\client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\jupyter_core\utils\__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\nbclient\client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\nbclient\client.py", line 1002, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\nbclient\client.py", line 800, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "C:\Users\Hannah.Williams\.conda\envs\sphinx-doc\lib\site-packages\nbclient\client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['x0 = [2362206.0, 3.0, 0.0]', '', "stateList = ['S', 'I', 'R']", '', "paramList = ['beta', 'gamma', 'N']"]
...
['    axarr[0].plot(t[:9], solution[:,0])', '    axarr[1].plot(t[:9], solution[:,1]) ', '    axarr[2].plot(t[:9], solution[:,2])', '', 'plt.show()']
-------------------

**Comment by hareball90** [comment]
try solution here https://github.com/executablebooks/jupyter-book/issues/948#issuecomment-686953893

**Comment by twomagpi** [comment]
fixed with the #114 release.
